#include <fam/apu.h>
#include <string.h>
#include <stdalign.h>
#include <assert.h>

#define DELTA_BUFFER_SIZE 256
#define BLEP_KERNEL_WIDTH 16
#define BLEP_KERNEL_PHASES 32

_Static_assert(DELTA_BUFFER_SIZE >= BLEP_KERNEL_WIDTH, "Delta buffer roll would overlap");

// TODO: Should this be configurable?
#define DC_BLOCK_CUTOFF_HZ 20.0

typedef enum {
    QUARTER_FRAME_CLOCK = 0,
    HALF_FRAME_CLOCK,
    THREEQUARTERS_FRAME_CLOCK,
    FRAME_CLOCK,
    FRAME_CLOCK_MODE1,

    FRAME_CLOCK_COUNT,
} FrameSequencerStep;

// NOTE: APU clock rate is half the CPU clock rate
// I'm using the CPU clock rate here because it's an integer
static const uint64_t CPU_CLOCK_RATE[2] = { 1789773, 1662607 };
// NOTE: Values are one more than written on Nesdev,
// because my APU clock function increments the counter at the beginning, 
// so at cycle 0 it's set to 1 immediately before comparing
static const uint16_t FRAME_SEQ_CLOCK[2][FRAME_CLOCK_COUNT] = {
    { 3729, 7457, 11186, 14915, 18641 }, // NTSC
    { 4157, 8314, 12470, 16627, 20783 } // PAL
};
// NOTE: These noise period values are half what is written on Nesdev, 
// because they're APU cycles instead of CPU cycles
static const uint16_t NOISE_PERIOD[2][16] = {
    { 2, 4, 8, 16, 32, 48, 64, 80, 101, 127, 190, 254, 381, 508, 1017, 2034 }, // NTSC
    { 2, 4, 7, 15, 30, 44, 59, 74, 94, 118, 177, 236, 354, 472, 945, 1889 }    // PAL
};

static const uint16_t DMC_RATE[2][16] = {
    { 428, 380, 340, 320, 286, 254, 226, 214, 190, 160, 142, 128, 106, 84, 72, 54 }, // NTSC
    { 398, 354, 316, 298, 276, 236, 210, 198, 176, 148, 132, 118, 98, 78, 66, 50 }   // PAL
};

static const uint8_t PULSE_SEQ[4] = {
    0b00000001,
    0b00000011,
    0b00001111,
    0b11111100
};

static const uint8_t TRIANGLE_SEQ[32] = {
    15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15
};

static const uint8_t LENGTH_TABLE[32] = {
    10, 254, 20, 2, 40, 4, 80, 6,
    160, 8, 60, 10, 14, 12, 26, 14,
    12, 16, 24, 18, 48, 20, 96, 22,
    192, 24, 72, 26, 16, 28, 32, 30
};

// Mixer output value tables
static const float PULSE_MIX_TABLE[31] = {
    0.000000f, 0.011609f, 0.022939f, 0.034001f, 0.044803f, 0.055355f, 0.065665f, 0.075741f, 
    0.085591f, 0.095224f, 0.104645f, 0.113862f, 0.122882f, 0.131710f, 0.140353f, 0.148816f, 
    0.157105f, 0.165226f, 0.173183f, 0.180981f, 0.188626f, 0.196120f, 0.203470f, 0.210679f, 
    0.217751f, 0.224689f, 0.231499f, 0.238182f, 0.244744f, 0.251186f, 0.257513f 
};

static const float TND_MIX_TABLE[203] = {
    0.000000f, 0.006700f, 0.013345f, 0.019936f, 0.026474f, 0.032959f, 0.039393f, 0.045775f, 
    0.052106f, 0.058386f, 0.064618f, 0.070800f, 0.076934f, 0.083020f, 0.089058f, 0.095050f, 
    0.100996f, 0.106896f, 0.112751f, 0.118561f, 0.124327f, 0.130049f, 0.135728f, 0.141365f, 
    0.146959f, 0.152512f, 0.158024f, 0.163494f, 0.168925f, 0.174315f, 0.179666f, 0.184978f, 
    0.190252f, 0.195487f, 0.200684f, 0.205845f, 0.210968f, 0.216054f, 0.221105f, 0.226120f, 
    0.231099f, 0.236043f, 0.240953f, 0.245828f, 0.250669f, 0.255477f, 0.260252f, 0.264993f, 
    0.269702f, 0.274379f, 0.279024f, 0.283638f, 0.288220f, 0.292771f, 0.297292f, 0.301782f, 
    0.306242f, 0.310673f, 0.315074f, 0.319446f, 0.323789f, 0.328104f, 0.332390f, 0.336649f, 
    0.340879f, 0.345083f, 0.349259f, 0.353408f, 0.357530f, 0.361626f, 0.365696f, 0.369740f, 
    0.373759f, 0.377752f, 0.381720f, 0.385662f, 0.389581f, 0.393474f, 0.397344f, 0.401189f, 
    0.405011f, 0.408809f, 0.412584f, 0.416335f, 0.420064f, 0.423770f, 0.427454f, 0.431115f, 
    0.434754f, 0.438371f, 0.441966f, 0.445540f, 0.449093f, 0.452625f, 0.456135f, 0.459625f, 
    0.463094f, 0.466543f, 0.469972f, 0.473380f, 0.476769f, 0.480138f, 0.483488f, 0.486818f, 
    0.490129f, 0.493421f, 0.496694f, 0.499948f, 0.503184f, 0.506402f, 0.509601f, 0.512782f, 
    0.515946f, 0.519091f, 0.522219f, 0.525330f, 0.528423f, 0.531499f, 0.534558f, 0.537601f, 
    0.540626f, 0.543635f, 0.546627f, 0.549603f, 0.552563f, 0.555507f, 0.558434f, 0.561346f, 
    0.564242f, 0.567123f, 0.569988f, 0.572838f, 0.575673f, 0.578493f, 0.581298f, 0.584088f, 
    0.586863f, 0.589623f, 0.592370f, 0.595101f, 0.597819f, 0.600522f, 0.603212f, 0.605887f, 
    0.608549f, 0.611197f, 0.613831f, 0.616452f, 0.619059f, 0.621653f, 0.624234f, 0.626802f, 
    0.629357f, 0.631899f, 0.634428f, 0.636944f, 0.639448f, 0.641939f, 0.644418f, 0.646885f, 
    0.649339f, 0.651781f, 0.654212f, 0.656630f, 0.659036f, 0.661431f, 0.663813f, 0.666185f, 
    0.668544f, 0.670893f, 0.673229f, 0.675555f, 0.677869f, 0.680173f, 0.682465f, 0.684746f, 
    0.687017f, 0.689276f, 0.691525f, 0.693763f, 0.695991f, 0.698208f, 0.700415f, 0.702611f, 
    0.704797f, 0.706973f, 0.709139f, 0.711294f, 0.713440f, 0.715576f, 0.717702f, 0.719818f, 
    0.721924f, 0.724021f, 0.726108f, 0.728186f, 0.730254f, 0.732313f, 0.734362f, 0.736402f, 
    0.738433f, 0.740455f, 0.742468f, 
};

// Autogenerated bandlimted step kernel
// Cutoff is 0.4 of the output sample rate (80% Nyquist)
static const float BLEP_KERNEL[BLEP_KERNEL_PHASES][BLEP_KERNEL_WIDTH] = {
    { -0.000000000f, -0.001666027f, +0.008197237f, -0.019861955f, +0.026131543f, -0.000000000f, -0.109865022f, +0.597064223f, +0.597064223f, -0.109865022f, -0.000000000f, +0.026131543f, -0.019861955f, +0.008197237f, -0.001666027f, -0.000000000f },
    { +0.000042731f, -0.001832097f, +0.008334043f, -0.019162368f, +0.023024740f, +0.006901497f, -0.118919758f, +0.574567403f, +0.618703362f, -0.099745411f, -0.007076219f, +0.029134631f, -0.020450188f, +0.008008936f, -0.001488213f, -0.000043088f },
    { +0.000084860f, -0.001985579f, +0.008419155f, -0.018356967f, +0.019833577f, +0.013594858f, -0.126908798f, +0.551285873f, +0.639414219f, -0.088565722f, -0.014292030f, +0.032014848f, -0.020922061f, +0.007769627f, -0.001299574f, -0.000086286f },
    { +0.000126149f, -0.002125705f, +0.008452654f, -0.017451781f, +0.016577513f, +0.020048490f, -0.133835245f, +0.527294708f, +0.659128818f, -0.076334753f, -0.021610710f, +0.034753342f, -0.021273128f, +0.007480087f, -0.001101097f, -0.000129343f },
    { +0.000166365f, -0.002251788f, +0.008434907f, -0.016453301f, +0.013276015f, +0.026232724f, -0.139706066f, +0.502670819f, +0.677782058f, -0.063065327f, -0.028994064f, +0.037331655f, -0.021499536f, +0.007141377f, -0.000893836f, -0.000172005f },
    { +0.000205285f, -0.002363225f, +0.008366553f, -0.015368432f, +0.009948462f, +0.032119904f, -0.144532020f, +0.477492677f, +0.695311949f, -0.048774290f, -0.036402558f, +0.039731829f, -0.021598056f, +0.006754845f, -0.000678904f, -0.000214021f },
    { +0.000242692f, -0.002459499f, +0.008248503f, -0.014204457f, +0.006614052f, +0.037684470f, -0.148327567f, +0.451840029f, +0.711659840f, -0.033482502f, -0.043795466f, +0.041936498f, -0.021566106f, +0.006322119f, -0.000457468f, -0.000255138f },
    { +0.000278382f, -0.002540179f, +0.008081929f, -0.012968997f, +0.003291709f, +0.042903030f, -0.151110768f, +0.425793615f, +0.726770636f, -0.017214809f, -0.051131008f, +0.043928988f, -0.021401778f, +0.005845105f, -0.000230746f, -0.000295108f },
    { +0.000312158f, -0.002604927f, +0.007868257f, -0.011669962f, +0.000000000f, +0.047754419f, -0.152903173f, +0.399434885f, +0.740593005f, +0.000000000f, -0.058366512f, +0.045693411f, -0.021103854f, +0.005325979f, +0.000000000f, -0.000333686f },
    { +0.000343839f, -0.002653491f, +0.007609157f, -0.010315515f, -0.003242959f, +0.052219759f, -0.153729691f, +0.372845701f, +0.753079568f, +0.018129248f, -0.065458571f, +0.047214760f, -0.020671825f, +0.004767180f, +0.000233473f, -0.000370632f },
    { +0.000373255f, -0.002685713f, +0.007306531f, -0.008914021f, -0.006419578f, +0.056282491f, -0.153618457f, +0.346108057f, +0.764187075f, +0.037136444f, -0.072363203f, +0.048478996f, -0.020105909f, +0.004171401f, +0.000468342f, -0.000405712f },
    { +0.000400249f, -0.002701526f, +0.006962502f, -0.007474006f, -0.009512877f, +0.059928418f, -0.152600681f, +0.319303786f, +0.773876576f, +0.056981367f, -0.079036030f, +0.049473144f, -0.019407055f, +0.003541579f, +0.000703255f, -0.000438701f },
    { +0.000424680f, -0.002700952f, +0.006579401f, -0.006004110f, -0.012506558f, +0.063145718f, -0.150710491f, +0.292514270f, +0.782113563f, +0.077620172f, -0.085432443f, +0.050185370f, -0.018576958f, +0.002880879f, +0.000936841f, -0.000469383f },
    { +0.000446419f, -0.002684104f, +0.006159752f, -0.004513043f, -0.015385079f, +0.065924962f, -0.147984765f, +0.265820163f, +0.788868112f, +0.099005497f, -0.091507783f, +0.050605072f, -0.017618059f, +0.002192690f, +0.001167717f, -0.000497551f },
    { +0.000465356f, -0.002651184f, +0.005706259f, -0.003009537f, -0.018133718f, +0.068259111f, -0.144462950f, +0.239301102f, +0.794114995f, +0.121086602f, -0.097217522f, +0.050722949f, -0.016533548f, +0.001480599f, +0.001394498f, -0.000523010f },
    { +0.000481395f, -0.002602482f, +0.005221789f, -0.001502307f, -0.020738636f, +0.070143513f, -0.140186884f, +0.213035435f, +0.797833785f, +0.143809501f, -0.102517442f, +0.050531082f, -0.015327357f, +0.000748386f, +0.001615805f, -0.000545580f },
    { +0.000494457f, -0.002538372f, +0.004709356f, -0.000000000f, -0.023186936f, +0.071575881f, -0.135200595f, +0.187099948f, +0.800008944f, +0.167117126f, -0.107363821f, +0.050023001f, -0.014004162f, -0.000000000f, +0.001830267f, -0.000565093f },
    { +0.000504480f, -0.002459310f, +0.004172107f, +0.001488845f, -0.025466713f, +0.072556266f, -0.129550108f, +0.161569604f, +0.800629885f, +0.190949494f, -0.111713617f, +0.049193750f, -0.012569365f, -0.000760455f, +0.002036534f, -0.000581396f },
    { +0.000511419f, -0.002365834f, +0.003613299f, +0.002955838f, -0.027567102f, +0.073087024f, -0.123283234f, +0.136517280f, +0.799691031f, +0.215243883f, -0.115524651f, +0.048039945f, -0.011029084f, -0.001528742f, +0.002233280f, -0.000594352f },
    { +0.000515247f, -0.002258556f, +0.003036288f, +0.004392785f, -0.029478322f, +0.073172762f, -0.116449364f, +0.112013525f, +0.797191842f, +0.239935028f, -0.118755794f, +0.046559829f, -0.009390137f, -0.002300507f, +0.002419216f, -0.000603841f },
    { +0.000515952f, -0.002138162f, +0.002444506f, +0.005791722f, -0.031191708f, +0.072820288f, -0.109099251f, +0.088126315f, +0.793136834f, +0.264955324f, -0.121367147f, +0.044753319f, -0.007660019f, -0.003071303f, +0.002593090f, -0.000609761f },
    { +0.000513542f, -0.002005407f, +0.001841445f, +0.007144958f, -0.032699745f, +0.072038547f, -0.101284792f, +0.064920829f, +0.787535578f, +0.290235038f, -0.123320225f, +0.042622050f, -0.005846879f, -0.003836610f, +0.002753701f, -0.000612030f },
    { +0.000508041f, -0.001861112f, +0.001230636f, +0.008445111f, -0.033996093f, +0.070838546f, -0.093058809f, +0.042459227f, +0.780402676f, +0.315702531f, -0.124578133f, +0.040169407f, -0.003959490f, -0.004591857f, +0.002899901f, -0.000610581f },
    { +0.000499490f, -0.001706155f, +0.000615635f, +0.009685142f, -0.035075607f, +0.069233273f, -0.084474822f, +0.020800445f, +0.771757729f, +0.341284492f, -0.125105739f, +0.037400553f, -0.002007222f, -0.005332449f, +0.003030607f, -0.000605372f },
    { +0.000487946f, -0.001541471f, +0.000000000f, +0.010858392f, -0.035934347f, +0.067237612f, -0.075586830f, +0.000000000f, +0.761625276f, +0.366906179f, -0.124869852f, +0.034322456f, +0.000000000f, -0.006053783f, +0.003144801f, -0.000596379f },
    { +0.000473485f, -0.001368046f, -0.000612725f, +0.011958608f, -0.036569591f, +0.064868246f, -0.066449084f, -0.019890189f, +0.750034724f, +0.392491662f, -0.123839379f, +0.030943897f, +0.002051725f, -0.006751279f, +0.003241544f, -0.000583597f },
    { +0.000456195f, -0.001186909f, -0.001219031f, +0.012979978f, -0.036979834f, +0.062143554f, -0.057115865f, -0.038821970f, +0.737020258f, +0.417964081f, -0.121985495f, +0.027275481f, +0.004137027f, -0.007420399f, +0.003319976f, -0.000567046f },
    { +0.000436183f, -0.000999129f, -0.001815457f, +0.013917154f, -0.037164785f, +0.059083504f, -0.047641264f, -0.056751113f, +0.722620731f, +0.443245903f, -0.119281791f, +0.023329639f, +0.006244540f, -0.008056677f, +0.003379327f, -0.000546765f },
    { +0.000413570f, -0.000805808f, -0.002398614f, +0.014765279f, -0.037125359f, +0.055709537f, -0.038078960f, -0.073637443f, +0.706879541f, +0.468259190f, -0.115704423f, +0.019120612f, +0.008362514f, -0.008655737f, +0.003418917f, -0.000522815f },
    { +0.000388489f, -0.000608076f, -0.002965198f, +0.015520006f, -0.036863663f, +0.052044451f, -0.028482007f, -0.089444968f, +0.689844492f, +0.492925862f, -0.111232258f, +0.014664445f, +0.010478860f, -0.009213324f, +0.003438167f, -0.000495278f },
    { +0.000361090f, -0.000407084f, -0.003512009f, +0.016177522f, -0.036382973f, +0.048112273f, -0.018902621f, -0.104141983f, +0.671567632f, +0.517167972f, -0.105847000f, +0.009978958f, +0.012581206f, -0.009725323f, +0.003436599f, -0.000464258f },
    { +0.000331532f, -0.000204000f, -0.004035965f, +0.016734558f, -0.035687709f, +0.043938132f, -0.009391977f, -0.117701161f, +0.652105088f, +0.540907979f, -0.099533319f, +0.005083718f, +0.014656950f, -0.010187790f, +0.003413845f, -0.000429881f },
};

typedef struct PulseChannel {
    union {
        struct {
            uint8_t volume_envelope_period : 4;
            uint8_t constant_volume : 1;
            uint8_t loop : 1;
            uint8_t duty_cycle : 2;

            uint8_t sweep_shift : 3;
            uint8_t sweep_negate : 1;
            uint8_t sweep_period : 3;
            uint8_t sweep_enabled : 1;

            uint16_t timer_period : 11;
            uint16_t length_counter_load : 5;
        };
        uint8_t raw_registers[4];
    };

    uint16_t timer_counter;

    uint8_t sequence_pos : 3;
    uint8_t length_counter;

    uint8_t sweep_counter;
    uint16_t sweep_target_period;

    int8_t envelope_counter;
    uint8_t envelope_volume;
} PulseChannel;

typedef struct TriangleChannel {
    union {
        struct {
            uint8_t linear_counter_load : 7;
            uint8_t loop : 1;

            uint8_t unused;

            uint16_t timer_period : 11;
            uint16_t length_counter_load : 5;
        };
        uint8_t raw_registers[4];
    };

    uint16_t timer_counter;

    uint8_t sequence : 5;
    uint8_t length_counter;

    uint8_t linear_counter;

    bool halt;

} TriangleChannel;

typedef struct NoiseChannel {
    union {
        struct {
            uint8_t volume_envelope_period : 4;
            uint8_t constant_volume : 1;
            uint8_t loop : 1;
            uint8_t unused0 : 2;
            
            uint8_t unused1;

            uint8_t period : 4;
            uint8_t unused2 : 3;
            uint8_t mode : 1;

            uint8_t unused3 : 3;
            uint8_t length_counter_load : 5;
        };
        uint8_t raw_registers[4];
    };

    uint16_t timer_counter;

    uint16_t shift_register : 15;

    uint8_t length_counter;

    int8_t envelope_counter;
    uint8_t envelope_volume;
} NoiseChannel;

typedef struct DPCMChannel {
    union {
        struct {
            uint8_t sample_rate : 4;
            uint8_t unused0 : 2;
            uint8_t loop : 1;
            uint8_t enable_irq : 1;

            uint8_t direct_load : 7;
            uint8_t unused1 : 1; // Unused sign bit for direct load

            uint8_t sample_address;

            uint8_t sample_length;
        };
        uint8_t raw_registers[4];
    };

    uint16_t timer_counter;

    uint16_t current_address;
    uint16_t bytes_remaining;
    uint8_t sample_buffer;
    bool buffer_filled;

    uint8_t shift_register;
    uint8_t bits_remaining;

    uint8_t output_level;
    uint8_t playing;

    FamDmcReadFn reader;
    void* reader_data;
} DPCMChannel;

typedef struct StatusRegister {
    uint8_t enable_pulse1 : 1;
    uint8_t enable_pulse2 : 1;
    uint8_t enable_triangle : 1;
    uint8_t enable_noise : 1;
    uint8_t enable_dmc : 1;
    uint8_t unused : 1; // NOTE: Open bus bit, not implemented
    uint8_t frame_interrupt : 1;
    uint8_t dmc_interrupt : 1;
} StatusRegister;

struct FamApu {
    PulseChannel pulse[2];
    TriangleChannel triangle;
    NoiseChannel noise;
    DPCMChannel dmc;
    union {
        StatusRegister status;
        uint8_t raw_status_register;
    };

    uint8_t sequencer_mode : 1;
    uint8_t frame_interrupt_inhibit : 1;

    uint8_t region;

    int64_t clock_counter;

    // Resampling
    uint32_t resample_rate;
    float last_mix;

    float delta_buffer[DELTA_BUFFER_SIZE + BLEP_KERNEL_WIDTH];
    uint64_t delta_increment;
    uint64_t delta_write_pos_fixed; // UQ32.32 fixed point
    uint32_t delta_read_pos; // Plain delta buffer index
    float delta_accumulator;

    // First-order high-pass on the output, see apu_dc_block.
    float dc_block_coeff;
    float dc_block_x_prev;
    float dc_block_y_prev;
};

static inline bool pulse_muted(const PulseChannel* pulse) {
    return pulse->timer_period < 0x08 || (!pulse->sweep_negate && pulse->sweep_target_period > 0x7FF);
}

static inline uint16_t pulse_get_target_period(const PulseChannel* pulse, bool is_pulse_1) {
    const uint16_t period_change = pulse->timer_period >> pulse->sweep_shift;
    return pulse->sweep_negate ? 
        pulse->timer_period - period_change - is_pulse_1
        : pulse->timer_period + period_change;
}

static void pulse_clock_envelope(PulseChannel* pulse) {
    if (--pulse->envelope_counter == 0) {
        pulse->envelope_counter = pulse->volume_envelope_period + 1;
        if (pulse->envelope_volume > 0) {
            pulse->envelope_volume--;
        } else if (pulse->loop) {
            pulse->envelope_volume = 0x0F;
        }
    }
}

static void pulse_clock_sweep(PulseChannel* pulse, bool is_pulse_1) {
    pulse->sweep_target_period = pulse_get_target_period(pulse, is_pulse_1);
    
    if (--pulse->sweep_counter == 0) {
        pulse->sweep_counter = pulse->sweep_period + 1;
        
        if (pulse->sweep_enabled && !pulse_muted(pulse) && (pulse->sweep_shift > 0)) {
            pulse->timer_period = pulse->sweep_target_period;
        }
    }
}

static void pulse_clock_length_counter(PulseChannel* pulse) {
    if (!pulse->loop && pulse->length_counter > 0) {
        pulse->length_counter--;
    }
}

static void pulse_clock_timer(PulseChannel* pulse) {
    if (pulse->timer_counter > 0) {
        pulse->timer_counter--;
    }

    if (pulse->timer_counter == 0) {
        pulse->sequence_pos--;
        pulse->timer_counter = pulse->timer_period + 1;
    }
}

static uint8_t pulse_get_output(const PulseChannel* pulse) {
    if (pulse_muted(pulse) || pulse->length_counter == 0) return 0;

    const uint8_t sequence = PULSE_SEQ[pulse->duty_cycle];
    const uint8_t value = (sequence >> pulse->sequence_pos) & 0b00000001;
    const uint8_t volume = pulse->constant_volume ? pulse->volume_envelope_period : pulse->envelope_volume;
    return value * volume;
}

static void triangle_clock_linear_counter(TriangleChannel* triangle) {
    if (triangle->halt) {
        triangle->linear_counter = triangle->linear_counter_load;
    } else if (triangle->linear_counter > 0) {
        triangle->linear_counter--;
    }

    if (!triangle->loop) {
        triangle->halt = false;
    }
}

static void triangle_clock_length_counter(TriangleChannel* triangle) {
    if (!triangle->loop && triangle->length_counter > 0) {
        triangle->length_counter--;
    }
}

static void triangle_clock_timer(TriangleChannel* triangle) {
    // NOTE: Triangle ticks at CPU clock rate (APU clock x2)
    for (int i = 0; i < 2; i++) {
        if (triangle->length_counter > 0 && triangle->linear_counter > 0) {

            if (triangle->timer_counter > 0) {
                triangle->timer_counter--;
            }

            if (triangle->timer_counter == 0) {
                triangle->sequence--;
                triangle->timer_counter = triangle->timer_period + 1;
            }
        }
    }
}

static uint8_t triangle_get_output(const TriangleChannel* triangle) {
    return TRIANGLE_SEQ[triangle->sequence];
}

static void noise_clock_envelope(NoiseChannel* noise) {
    if (--noise->envelope_counter == 0) {
        noise->envelope_counter = noise->volume_envelope_period + 1;
        if (noise->envelope_volume > 0) {
            noise->envelope_volume--;
        } else if (noise->loop) {
            noise->envelope_volume = 0x0F;
        }
    }
}

static void noise_clock_length_counter(NoiseChannel* noise) {
    if (!noise->loop && noise->length_counter > 0) {
        noise->length_counter--;
    }
}

static void noise_clock_timer(NoiseChannel* noise, uint8_t region) {
    if (noise->timer_counter > 0) {
        noise->timer_counter--;
    }

    if (noise->timer_counter == 0) {
        const uint8_t mode_bit_index = noise->mode ? 6 : 1;
        const uint8_t mode_bit = (uint8_t)noise->shift_register >> mode_bit_index;
        const uint8_t feedback_bit = (noise->shift_register ^ mode_bit) & 1;

        noise->shift_register >>= 1;
        noise->shift_register |= (feedback_bit << 14);

        noise->timer_counter = NOISE_PERIOD[region][noise->period];
    }
}

static uint8_t noise_get_output(const NoiseChannel* noise) {
    if (noise->length_counter == 0 || noise->shift_register & 1) {
        return 0;
    }

    const uint8_t volume = noise->constant_volume ? noise->volume_envelope_period : noise->envelope_volume;
    return volume;
}

static void dmc_load_sample(DPCMChannel* dmc) {
    dmc->current_address = 0xC000 + (dmc->sample_address << 6);
    dmc->bytes_remaining = (dmc->sample_length << 4) + 1;
}

static bool dmc_try_fill_buffer(DPCMChannel* dmc) {
    bool interrupt = false;
    
    if (!dmc->buffer_filled && dmc->bytes_remaining != 0) {
        // NOTE: On real hardware, the CPU is stalled for 1-4 CPU cycles to read a sample byte
        // There's no CPU in fam, so I'm not modeling this behaviour

        if (dmc->reader != NULL) {
            dmc->sample_buffer = dmc->reader(dmc->reader_data, dmc->current_address);
        }
        dmc->buffer_filled = true;

        if (dmc->current_address == 0xFFFF) {
            dmc->current_address = 0x8000;
        } else {
            dmc->current_address++;
        }

        dmc->bytes_remaining--;
        if (dmc->bytes_remaining == 0) {
            if (dmc->loop) {
                dmc_load_sample(dmc);
            } else if (dmc->enable_irq) {
                interrupt = true;
            }
        }
    }

    return interrupt;
}

static bool dmc_clock_timer(DPCMChannel* dmc, uint8_t region) {
    bool interrupt = false;

    // NOTE: DMC ticks at CPU rate
    for (int i = 0; i < 2; i++) {
        if (dmc->timer_counter > 0) {
            dmc->timer_counter--;
        }

        // DMA reader
        interrupt |= dmc_try_fill_buffer(dmc);

        // Output unit
        if (dmc->timer_counter == 0) {
            if (dmc->playing) {
                if (dmc->shift_register & 1) {
                    if (dmc->output_level <= 125) {
                        dmc->output_level += 2;
                    }
                } else if (dmc->output_level >= 2) {
                    dmc->output_level -= 2;
                }
            }

            dmc->shift_register >>= 1;

            if (dmc->bits_remaining > 0) {
                dmc->bits_remaining--;
            }

            if (dmc->bits_remaining == 0) {
                dmc->bits_remaining = 8;
                if (!dmc->buffer_filled) {
                    dmc->playing = false;
                } else {
                    dmc->playing = true;
                    dmc->shift_register = dmc->sample_buffer;
                    dmc->buffer_filled = false;
                }
            }

            dmc->timer_counter = DMC_RATE[region][dmc->sample_rate];
        }
    }

    return interrupt;
}

static void apu_clock_quarter_frame(FamApu* apu) {
    pulse_clock_envelope(apu->pulse);
    pulse_clock_envelope(apu->pulse + 1);

    triangle_clock_linear_counter(&apu->triangle);

    noise_clock_envelope(&apu->noise);
}

static void apu_clock_half_frame(FamApu* apu) {
    pulse_clock_sweep(apu->pulse, true);
    pulse_clock_sweep(apu->pulse + 1, false);

    pulse_clock_length_counter(apu->pulse);
    pulse_clock_length_counter(apu->pulse + 1);

    triangle_clock_length_counter(&apu->triangle);

    noise_clock_length_counter(&apu->noise);
}

static void apu_clock_frame(FamApu* apu) {
    if (apu->sequencer_mode == 0 && !apu->frame_interrupt_inhibit) {
        apu->status.frame_interrupt = 1;
    }
    apu->clock_counter = 0;
}

static void apu_write_pulse_register(FamApu* apu, int index, int offset, uint8_t data) {
    PulseChannel* pulse = apu->pulse + index;
    pulse->raw_registers[offset] = data;

    const bool enabled = index == 1 ? apu->status.enable_pulse2 : apu->status.enable_pulse1;

    switch (offset) {
        case 0:
            // Nesdev: The duty cycle is changed (see table below), but the sequencer's current position isn't affected.
            // So I guess nothing happens? Double check if sounds weird
            break;
        case 1:
            pulse->sweep_target_period = pulse_get_target_period(pulse, index == 0);
            pulse->sweep_counter = pulse->sweep_period + 1;
            break;
        case 2:
            pulse->sweep_target_period = pulse_get_target_period(pulse, index == 0);
            break;
        case 3:
            // Nesdev: The sequencer is immediately restarted at the first value of the current sequence. 
            // The envelope is also restarted. The period divider is not reset.
            pulse->sweep_target_period = pulse_get_target_period(pulse, index == 0);
            pulse->sequence_pos = 0;

            pulse->envelope_counter = pulse->volume_envelope_period + 1;
            pulse->envelope_volume = 0x0F;

            if (enabled) {
                pulse->length_counter = LENGTH_TABLE[pulse->length_counter_load];
            }
            break;
        default:
            break;
    }
}

static void apu_write_triangle_register(FamApu* apu, int offset, uint8_t data) {
    TriangleChannel* triangle = &apu->triangle;
    triangle->raw_registers[offset] = data;
    
    switch (offset) {
        case 0:
        case 1:
        case 2:
            break;
        case 3:
            // Nesdev: Sets the linear counter reload flag
            // AKA halt
            triangle->halt = true;

            if (apu->status.enable_triangle) {
                triangle->length_counter = LENGTH_TABLE[triangle->length_counter_load];
            }
            break;
        default:
            break;
    }
}

static void apu_write_noise_register(FamApu* apu, int offset, uint8_t data) {
    NoiseChannel* noise = &apu->noise;
    noise->raw_registers[offset] = data;

    switch (offset) {
        case 0:
        case 1:
        case 2:
            break;
        case 3:
            noise->envelope_counter = noise->volume_envelope_period + 1;
            noise->envelope_volume = 0x0F;

            if (apu->status.enable_noise) {
                noise->length_counter = LENGTH_TABLE[noise->length_counter_load];
            }
            break;
        default:
            break;
    }
}

static void apu_write_dmc_register(FamApu* apu, int offset, uint8_t data) {
    DPCMChannel* dmc = &apu->dmc;
    dmc->raw_registers[offset] = data;

    switch (offset) {
        case 0:
            if (!dmc->enable_irq) {
                apu->status.dmc_interrupt = false;
            }
            break;
        case 1:
            dmc->output_level = dmc->direct_load;
            break;
        case 2:
        case 3:
        default:
            break;
    }
}

static float apu_mix(const FamApu* apu) {
    uint8_t pulse_sum = pulse_get_output(apu->pulse);
    pulse_sum += pulse_get_output(apu->pulse + 1);

    const float pulse_out = PULSE_MIX_TABLE[pulse_sum];

    const uint8_t triangle = triangle_get_output(&apu->triangle);
    const uint8_t noise = noise_get_output(&apu->noise);
    const uint8_t dmc = apu->dmc.output_level;

    const float tnd_out = TND_MIX_TABLE[3 * triangle + 2 * noise + dmc];

    return pulse_out + tnd_out;
}

static void apu_clock(FamApu* apu) {
    apu->clock_counter++;

    const uint16_t* frame_seq_clock = FRAME_SEQ_CLOCK[apu->region];
    if (apu->clock_counter == frame_seq_clock[QUARTER_FRAME_CLOCK]) {
        apu_clock_quarter_frame(apu);
    } else if (apu->clock_counter == frame_seq_clock[HALF_FRAME_CLOCK]) {
        apu_clock_quarter_frame(apu);
        apu_clock_half_frame(apu);
    } else if (apu->clock_counter == frame_seq_clock[THREEQUARTERS_FRAME_CLOCK]) {
        apu_clock_quarter_frame(apu);
    } else if ((apu->sequencer_mode == 0 && apu->clock_counter == frame_seq_clock[FRAME_CLOCK]) 
        || (apu->sequencer_mode == 1 && apu->clock_counter == frame_seq_clock[FRAME_CLOCK_MODE1])) {
        apu_clock_quarter_frame(apu);
        apu_clock_half_frame(apu);
        apu_clock_frame(apu);
    }

    pulse_clock_timer(apu->pulse);
    pulse_clock_timer(apu->pulse + 1);
    triangle_clock_timer(&apu->triangle);
    noise_clock_timer(&apu->noise, apu->region);
    apu->status.dmc_interrupt |= dmc_clock_timer(&apu->dmc, apu->region);
}

// First-order high-pass, applied to every sample
// Gets rid of mixer output's unipolarity and moving resting level
// Additionally, delta_accumulator sums float deltas forever which accumulates rounding errors
// as a random walk. This also gets rid of that.
// Written in difference form so it operates on deltas rather than absolute
// levels, which keeps it well conditioned even with a coefficient near 1
static inline float apu_dc_block(FamApu* apu, float x) {
    const float y = apu->dc_block_coeff * (apu->dc_block_y_prev + x - apu->dc_block_x_prev);
    apu->dc_block_x_prev = x;
    apu->dc_block_y_prev = y;
    return y;
}

// Integrates the delta buffer and outputs samples
// Drained buffer slots are cleared afterwards
// NOTE: count must not make the read position exceed buffer size
static inline int apu_drain_samples(FamApu* apu, uint32_t count, float* out_samples) {
    int samples_processed = 0;
    for (uint32_t i = 0; i < count; i++) {
        apu->delta_accumulator += apu->delta_buffer[apu->delta_read_pos];
        apu->delta_buffer[apu->delta_read_pos++] = 0.0f;
        // DC block is a recursive filter, so it needs to run for all samples regardless of output
        const float sample = apu_dc_block(apu, apu->delta_accumulator);
        if (out_samples) {
            out_samples[i] = sample;
            samples_processed++;
        }
    }
    return samples_processed;
}

size_t fam_apu_get_memory_required(void) {
    return sizeof(FamApu);
}

size_t fam_apu_get_memory_alignment(void) {
    return alignof(FamApu);
}

FamResult fam_apu_init(FamApu** out_apu, void* memory, FamRegion region, uint32_t resample_rate) {
    if (out_apu == NULL || memory == NULL) {
        return FAM_ERROR_INVALID_ARGUMENT;
    }

    if (region > FAM_REGION_PAL) {
        return FAM_ERROR_INVALID_ARGUMENT;
    }

    FamApu* apu = (FamApu*)memory;
    memset(apu, 0, sizeof(FamApu));

    apu->region = region;
    apu->resample_rate = resample_rate;

    // TODO: Should these be in their own function?
    apu->noise.shift_register = 1;
    apu->noise.timer_counter = NOISE_PERIOD[region][0];

    float initial_mix = apu_mix(apu);
    apu->last_mix = initial_mix;
    apu->delta_buffer[0] = initial_mix;

    // a = fs / (fs + 2*pi*fc), the standard first-order RC high-pass
    static const double pi = 3.141592653589793;
    const double output_rate = resample_rate ? (double)resample_rate : (double)CPU_CLOCK_RATE[region] / 2.0;
    apu->dc_block_coeff = (float)(output_rate / (output_rate + 2 * pi * DC_BLOCK_CUTOFF_HZ));
    apu->dc_block_x_prev = initial_mix;

    if (resample_rate == 0) {
        apu->delta_increment = 1ull << 32;
    } else {
        // Shifting left by 33 -> 32 fractional bits and an additional shift to double it, 
        // because I divide by the CPU clock rate which is double the APU clock rate
        apu->delta_increment = ((uint64_t)resample_rate << 33) / CPU_CLOCK_RATE[region];
    }

    *out_apu = apu;
    return FAM_SUCCESS;
}

void fam_apu_shutdown(FamApu* apu) {
    if (apu == NULL) {
        return;
    }

    apu->dmc.reader = NULL;
    apu->dmc.reader_data = NULL;
}

FamRegion fam_apu_get_region(const FamApu* apu) {
    return apu->region;
}

FamResult fam_apu_write_register(FamApu* apu, uint16_t reg, uint8_t data) {
    switch (reg) {
        case FAM_REGISTER_PULSE1_0:
        case FAM_REGISTER_PULSE1_1:
        case FAM_REGISTER_PULSE1_2:
        case FAM_REGISTER_PULSE1_3: {
            int offset = (int)reg - FAM_REGISTER_PULSE1_0;
            apu_write_pulse_register(apu, 0, offset, data);
            break;
        }
        case FAM_REGISTER_PULSE2_0:
        case FAM_REGISTER_PULSE2_1:
        case FAM_REGISTER_PULSE2_2:
        case FAM_REGISTER_PULSE2_3: {
            int offset = (int)reg - FAM_REGISTER_PULSE2_0;
            apu_write_pulse_register(apu, 1, offset, data);
            break;
        }
        case FAM_REGISTER_TRIANGLE_0:
        case FAM_REGISTER_TRIANGLE_1:
        case FAM_REGISTER_TRIANGLE_2:
        case FAM_REGISTER_TRIANGLE_3: {
            int offset = (int)reg - FAM_REGISTER_TRIANGLE_0;
            apu_write_triangle_register(apu, offset, data);
            break;
        }
        case FAM_REGISTER_NOISE_0:
        case FAM_REGISTER_NOISE_1:
        case FAM_REGISTER_NOISE_2:
        case FAM_REGISTER_NOISE_3: {
            int offset = (int)reg - FAM_REGISTER_NOISE_0;
            apu_write_noise_register(apu, offset, data);
            break;
        }
        case FAM_REGISTER_DMC_0:
        case FAM_REGISTER_DMC_1:
        case FAM_REGISTER_DMC_2:
        case FAM_REGISTER_DMC_3: {
            int offset = (int)reg - FAM_REGISTER_DMC_0;
            apu_write_dmc_register(apu, offset, data);
            break;
        }
        case FAM_REGISTER_STATUS: {
            // Only set first 5 bits
            apu->raw_status_register = (apu->raw_status_register & 0b11100000) | (data & 0b00011111);
            // Always clear DMC IRQ
            apu->status.dmc_interrupt = false;
            if (!apu->status.enable_pulse1) {
                apu->pulse->length_counter = 0;
            }
            if (!apu->status.enable_pulse2) {
                (apu->pulse + 1)->length_counter = 0;
            }
            if (!apu->status.enable_triangle) {
                apu->triangle.length_counter = 0;
            }
            if (!apu->status.enable_noise) {
                apu->noise.length_counter = 0;
            }
            if (!apu->status.enable_dmc) {
                apu->dmc.bytes_remaining = 0;
            } else if (apu->dmc.bytes_remaining == 0) {
                dmc_load_sample(&apu->dmc);
                apu->status.dmc_interrupt |= dmc_try_fill_buffer(&apu->dmc);
            }
            break;
        }
        case FAM_REGISTER_FRAME_COUNTER: {
            // NOTE: On real hardware, there's a 3-4 cycle delay depending on when the write happened.
            // There's no CPU emulation in fam, so I'm not modeling this behaviour
            apu->clock_counter = 0;
            apu->sequencer_mode = data >> 7;
            apu->frame_interrupt_inhibit = (data >> 6) & 1;
            // Nesdev: Interrupt inhibit flag. If set, the frame interrupt flag is cleared, otherwise it is unaffected.
            if (apu->frame_interrupt_inhibit) {
                apu->status.frame_interrupt = 0;
            }
            // Nesdev: If the mode flag is set, then both "quarter frame" and "half frame" signals are also generated.
            if (apu->sequencer_mode == 1) {
                apu_clock_quarter_frame(apu);
                apu_clock_half_frame(apu);
            }
            break;
        }
        default:
            return FAM_ERROR_INVALID_ARGUMENT;
    }

    return FAM_SUCCESS;
}

FamResult fam_apu_read_register(FamApu* apu, uint16_t reg, uint8_t* out_data) {
    switch (reg) {
        case FAM_REGISTER_PULSE1_0:
        case FAM_REGISTER_PULSE1_1:
        case FAM_REGISTER_PULSE1_2:
        case FAM_REGISTER_PULSE1_3:
        case FAM_REGISTER_PULSE2_0:
        case FAM_REGISTER_PULSE2_1:
        case FAM_REGISTER_PULSE2_2:
        case FAM_REGISTER_PULSE2_3:
        case FAM_REGISTER_TRIANGLE_0:
        case FAM_REGISTER_TRIANGLE_1:
        case FAM_REGISTER_TRIANGLE_2:
        case FAM_REGISTER_TRIANGLE_3:
        case FAM_REGISTER_NOISE_0:
        case FAM_REGISTER_NOISE_1:
        case FAM_REGISTER_NOISE_2:
        case FAM_REGISTER_NOISE_3:
            return FAM_ERROR_WRITE_ONLY;
        case FAM_REGISTER_STATUS: {
            // NOTE: On real hardware, bit 5 is open bus.
            // I'm not modeling open bus behaviour, so it's always zero
            *out_data = apu->raw_status_register & 0b11011111;
            if (apu->pulse[0].length_counter == 0) *out_data &= 0b11111110;
            if (apu->pulse[1].length_counter == 0) *out_data &= 0b11111101;
            if (apu->triangle.length_counter == 0) *out_data &= 0b11111011;
            if (apu->noise.length_counter == 0) *out_data &= 0b11110111;
            if (apu->dmc.bytes_remaining == 0) *out_data &= 0b11101111;
            apu->status.frame_interrupt = 0;
            break;
        }
        case FAM_REGISTER_FRAME_COUNTER:
            return FAM_ERROR_WRITE_ONLY;
        default:
            return FAM_ERROR_INVALID_ARGUMENT;
    }

    return FAM_SUCCESS;
}

void fam_apu_set_dmc_reader(FamApu* apu, FamDmcReadFn reader, void* user_data) {
    apu->dmc.reader = reader;
    apu->dmc.reader_data = user_data;
}

int fam_apu_run(FamApu* apu, int cycles, float* out_samples) {
    uint32_t samples_processed = 0;

    for (int i = 0; i < cycles; i++) {
        uint64_t next_delta_write_pos = apu->delta_write_pos_fixed + apu->delta_increment;
        // Roll delta buffer if needed
        if (next_delta_write_pos >= (uint64_t)DELTA_BUFFER_SIZE << 32) {
            samples_processed += apu_drain_samples(apu, DELTA_BUFFER_SIZE - apu->delta_read_pos, 
                out_samples ? out_samples + samples_processed : NULL);
            apu->delta_read_pos = 0;
            
            // Move BLEP kernel tail to front
            memcpy(apu->delta_buffer, apu->delta_buffer + DELTA_BUFFER_SIZE, BLEP_KERNEL_WIDTH * sizeof(float));
            memset(apu->delta_buffer + DELTA_BUFFER_SIZE, 0, BLEP_KERNEL_WIDTH * sizeof(float));

            next_delta_write_pos -= (uint64_t)DELTA_BUFFER_SIZE << 32;
        }

        apu_clock(apu);

        const float mix = apu_mix(apu);
        const float delta = mix - apu->last_mix;
        if (delta != 0.0f) {
            // BLEP splat
            const uint32_t delta_buffer_index = next_delta_write_pos >> 32;
            const uint32_t phase = (next_delta_write_pos >> 27) & (BLEP_KERNEL_PHASES - 1); // top 5 fraction bits
            const float* k = BLEP_KERNEL[phase];
            for (int j = 0; j < BLEP_KERNEL_WIDTH; j++) {
                apu->delta_buffer[delta_buffer_index + j] += delta * k[j];
            }

            apu->last_mix = mix;
        }
        
        apu->delta_write_pos_fixed = next_delta_write_pos;
    }

    samples_processed += apu_drain_samples(apu, (apu->delta_write_pos_fixed >> 32) - apu->delta_read_pos, 
        out_samples ? out_samples + samples_processed : NULL);
    return samples_processed;
}

double fam_apu_get_clock_rate(const FamApu* apu) {
    return (double)CPU_CLOCK_RATE[apu->region] / 2.0;
}

int fam_apu_get_cycles_for_samples(const FamApu* apu, int sample_count) {
    const uint64_t target = ((apu->delta_write_pos_fixed >> 32) + (uint64_t)sample_count) << 32;
    const uint64_t distance = target - apu->delta_write_pos_fixed;
    return (int)((distance + apu->delta_increment - 1) / apu->delta_increment);  // ceil
}